# Setup
title:        Commonplace Devblog
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       WB Kim
  url:        http://wonbae.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
