# Setup
title:        Commonplace Dev Note
tagline:      개발 비망록, Think about Thinking
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       WB Kim, Metamong
  url:        http://wonbae.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
